### ISSUE TITLE
torch==2.2.0 run error

### ISSUE THREAD

**Issue by Zjq9409** [intel/xFasterTransformer#233]
Traceback (most recent call last):
  File "/home/jane/intel_aigc/test_xfaster.py", line 1, in <module>
    import xfastertransformer
  File "/home/jane/anaconda3/envs/llamacpp/lib/python3.9/site-packages/xfastertransformer/__init__.py", line 31, in <module>
    torch.classes.load_library(os.path.dirname(os.path.abspath(__file__)) + "/libxfastertransformer_pt.so")
  File "/home/jane/anaconda3/envs/llamacpp/lib/python3.9/site-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/home/jane/anaconda3/envs/llamacpp/lib/python3.9/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/home/jane/anaconda3/envs/llamacpp/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/jane/anaconda3/envs/llamacpp/lib/python3.9/site-packages/xfastertransformer/libxfastertransformer_pt.so: undefined symbol: _ZN5torch7LibraryC1ENS0_4KindESsN3c108optionalINS2_11DispatchKeyEEEPKcj

(llamacpp) jane@intel-spr-hbm-01:~/intel_aigc$ pip list  | grep torch
WARNING: Ignoring invalid distribution -vidia-cublas-cu12 (/home/jane/anaconda3/envs/llamacpp/lib/python3.9/site-packages)
torch                         2.2.0

xft 在torch==2.2.0上报错。

**Comment by Duyi-Wang** [comment]
因为xft编译时使用的是torch 2.0版本的libtorch.so，看起来并不支持后向或前向兼容，torch版本的依赖也因此写入在whl包中了。如果需要和其他版本torch兼容运行，需要重新编译。

**Comment by Zjq9409** [comment]
怎么编译呢？需要修改什么么？

**Comment by Duyi-Wang** [comment]
编译环境中安装对应版本的torch即可。另外打包wheel包的时候，需要在setup.py修改下对应的依赖，来避免pip install时候的警告。
