### ISSUE TITLE
Error install xfastertransformer on CentOS 7.6

### ISSUE THREAD

**Issue by bin1guo** [intel/xFasterTransformer#244]
在centOS7 上pip install xfastertransformer后， import xfastertransformer 提示如下错误

```
>>> import xfastertransformer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.conda/envs/xft_test/lib/python3.8/site-packages/xfastertransformer/__init__.py", line 31, in <module>
    torch.classes.load_library(os.path.dirname(os.path.abspath(__file__)) + "/libxfastertransformer_pt.so")
  File "/root/.conda/envs/xft_test/lib/python3.8/site-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/root/.conda/envs/xft_test/lib/python3.8/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/root/.conda/envs/xft_test/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.conda/envs/xft_test/lib/python3.8/site-packages/xfastertransformer/libxfastertransformer_pt.so)
```

**Comment by bin1guo** [comment]
Solved through update libstdc++.so.6
