### ISSUE TITLE
error quantization with AWQ + AutoGPTQ

### ISSUE THREAD

**Issue by zhm-algo** [intel/xFasterTransformer#312]
xft docker image version 1.4.0

1. follow the instruction from https://github.com/intel/xFasterTransformer/tree/feature/awq_qptq/tools/quantization
2. pip install -e .
    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xfastertransformer 1.4.0 requires torch<2.1.0,>=2.0.0, but you have torch 2.2.2 which is incompatible.
3. python -m awq.entry --model_path /data/Llama-2-13b-chat-hf/ --w_bit 8 --q_group_size 128  --run_awq --dump_awq awq_cache/llama2_13b_w8.pt --dump_model awq_model/
Traceback (most recent call last):
  File "/usr/bin/python3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/bin/python3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/xFasterTransformer/3rdparty/llm-awq/awq/entry.py", line 1, in <module>
    from lm_eval import evaluator, tasks
  File "/usr/bin/python3.8/lib/python3.8/site-packages/lm_eval/__init__.py", line 1, in <module>
    from .evaluator import evaluate, simple_evaluate
  File "/usr/bin/python3.8/lib/python3.8/site-packages/lm_eval/evaluator.py", line 11, in <module>
    import lm_eval.api.metrics
  File "/usr/bin/python3.8/lib/python3.8/site-packages/lm_eval/api/metrics.py", line 7, in <module>
    import evaluate as hf_evaluate
  File "/usr/bin/python3.8/lib/python3.8/site-packages/evaluate/__init__.py", line 29, in <module>
    from .evaluation_suite import EvaluationSuite
  File "/usr/bin/python3.8/lib/python3.8/site-packages/evaluate/evaluation_suite/__init__.py", line 7, in <module>
    from datasets import Dataset, DownloadConfig, DownloadMode, load_dataset
  File "/usr/bin/python3.8/lib/python3.8/site-packages/datasets/__init__.py", line 18, in <module>
    from .arrow_dataset import Dataset
  File "/usr/bin/python3.8/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 67, in <module>
    from .arrow_reader import ArrowReader
  File "/usr/bin/python3.8/lib/python3.8/site-packages/datasets/arrow_reader.py", line 32, in <module>
    from .download.download_config import DownloadConfig
  File "/usr/bin/python3.8/lib/python3.8/site-packages/datasets/download/__init__.py", line 9, in <module>
    from .download_manager import DownloadManager, DownloadMode
  File "/usr/bin/python3.8/lib/python3.8/site-packages/datasets/download/download_manager.py", line 33, in <module>
    from ..utils.file_utils import (
  File "/usr/bin/python3.8/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 39, in <module>
    from .extract import ExtractManager
  File "/usr/bin/python3.8/lib/python3.8/site-packages/datasets/utils/extract.py", line 3, in <module>
    import lzma
  File "/usr/bin/python3.8/lib/python3.8/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
root@84f20ebe58be:/data/xFasterTransformer/3rdparty/llm-awq# pip install _lzma
ERROR: Invalid requirement: '_lzma'
root@84f20ebe58be:/data/xFasterTransformer/3rdparty/llm-awq# pip install lzma
ERROR: Could not find a version that satisfies the requirement lzma (from versions: none)
ERROR: No matching distribution found for lzma

**Comment by miaojinc** [comment]
xft docker image limits torch version <2.1.0,>=2.0.0. I will try to build a new image for quantization.

**Comment by miaojinc** [comment]
hi @zhm-algo  Haoming, I have just pushed a new docker image for llama2 quantization: https://hub.docker.com/r/wisespreading/xft-awq-gptq
You could use it to quantize LLM and convert weights files. And use the original image to inference.

**Comment by zhm-algo** [comment]
docker pull wisespreading/xft-awq-gptq
failed with error manifest unknown

**Comment by miaojinc** [comment]
I re-uploaded the image, please have a try, thanks.

**Comment by zhm-algo** [comment]
it works, thanks.

**Comment by zhm-algo** [comment]
i made a gptq model of Llama-2-7b, when i try to convert the model in the docker of xft:1.5.0, several error occured.

 python -c 'import xfastertransformer as xft; xft.LlamaConvert().convert("/data/gptq_model/Llama-2-7B-Chat-hf","/data/gptq_model/Llama-2-7B-Chat-cpu", from_quantized_model="gptq")'

ModuleNotFoundError: No module named 'auto_gptq'

pip install auto_gptq

ModuleNotFoundError: No module named '_lzma'

so how to install lzma

and also some warning occurs, such as

[Warning] The version of `transformers` in model configuration is 4.34.1, and version installed is 4.38.1. This model convert error may be caused by transformers version compatibility. You can downgrade or reinstall transformers by `pip install transformers==4.34.1 --force-reinstall` and try again.

do i need to downgrade the transformer to lower version ？
