### ISSUE TITLE
Can't find the libmklml_intel.so

### ISSUE THREAD

**Issue by oldmikeyang** [intel/xFasterTransformer#47]
The following is the error
(cpu-xfaster) llm@SPR-ARC:~/xFasterTransformer/build$ python -d -m xfastertransformer.example.web_demo
Traceback (most recent call last):
  File "/home/llm/miniconda3/envs/cpu-xfaster/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/llm/miniconda3/envs/cpu-xfaster/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/llm/miniconda3/envs/cpu-xfaster/lib/python3.10/site-packages/xfastertransformer/__init__.py", line 4, in <module>
    torch.classes.load_library(os.path.dirname(os.path.abspath(__file__)) + "/libxfastertransformer_pt.so")
  File "/home/llm/miniconda3/envs/cpu-xfaster/lib/python3.10/site-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/home/llm/miniconda3/envs/cpu-xfaster/lib/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/llm/miniconda3/envs/cpu-xfaster/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ****libmklml_intel.so**: cannot open shared object file: No such file or directory**

The following is the oneDNN from Intel oneAPI 23.03, there is no file name is **libmklml_intel.so**
(cpu-xfaster) llm@SPR-ARC:/opt/intel/oneapi$ find . -name '*_intel.so'
./mkl/2023.2.0/lib/ia32/libmkl_intel.so

**Comment by Duyi-Wang** [comment]
This dependency has been removed and will be released in the next version.
For version 1.0.0, please set mklml manually:
- Firstly download mklml
```
wget https://github.com/oneapi-src/oneDNN/releases/download/v0.21/mklml_lnx_2019.0.5.20190502.tgz \
    && tar -xzf mklml_lnx_2019.0.5.20190502.tgz \
    && rm -f mklml_lnx_2019.0.5.20190502.tgz
```
- Then export it into PATH
 ```
export LD_LIBRARY_PATH=${where is your mklml directory}/mklml_lnx_2019.0.5.20190502/lib:$LD_LIBRARY_PATH
```

**Comment by Duyi-Wang** [comment]
fixed by https://github.com/intel/xFasterTransformer/pull/42
