### ISSUE TITLE
ModuleNotFoundError: No module named 'xfastertransformer.tools'

### ISSUE THREAD

**Issue by JunxiChhen** [intel/xFasterTransformer#83]
I'm using commit f205d37 to compile xfastertransformer.
When "import xfastertransformer", it shows error:
```
2: Traceback (most recent call last):
2:   File "/home/workspace/xFasterTransformer/benchmark/benchmark.py", line 89, in <module>
2:     import xfastertransformer
2:   File "/root/anaconda3/envs/llm/lib/python3.9/site-packages/xfastertransformer-1.0.0-py3.9-linux-x86_64.egg/xfastertransformer/__init__.py", line 22, in <module>
2:     from .tools import LlamaConvert
2: ModuleNotFoundError: No module named 'xfastertransformer.tools'
```

**Comment by pujiang2018** [comment]
@Duyi-Wang could you pls fix this?

**Comment by Duyi-Wang** [comment]
PR https://github.com/intel/xFasterTransformer/pull/84

**Comment by JunxiChhen** [comment]
Test passed.
