### ISSUE TITLE
AttributeError: module xfastertransformer has no attribute AutoModel

### ISSUE THREAD

**Issue by marvin-Yu** [intel/xFasterTransformer#95]
```shell
(demo) [root@iZ2ze5jp679eomnr2xu3s0Z web_demo]# python ChatGLM2.py
[INFO] xfastertransformer is not installed in pip, using source code.
Traceback (most recent call last):
  File "ChatGLM2.py", line 68, in <module>
    demo = ChatGLM2Demo(args.token_path, args.model_path, dtype=args.dtype)
  File "/mnt/xFasterTransformer/examples/web_demo/demo_utils.py", line 61, in __init__
    self.model = xfastertransformer.AutoModel.from_pretrained(model_path, dtype=dtype)
  File "/mnt/xFasterTransformer/examples/web_demo/../../src/xfastertransformer/__init__.py", line 59, in __getattr__                                                                                                        
    raise AttributeError("module {} has no attribute {}".format(self.__name__, name))
AttributeError: module xfastertransformer has no attribute AutoModel
```

**Comment by Duyi-Wang** [comment]
https://github.com/intel/xFasterTransformer/pull/91
